name: wp_02_twittery
description: Twittery — Twitter Clone
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  intl_phone_field: ^3.1.0
  pinput: ^2.2.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Icon/
    - assets/Placeholder/
