name: Cherp App
description: Cherp — Twitter Clone
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  intl_phone_field: ^3.1.0
  pinput: ^2.2.21
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  image_path: "assets/Icon/App/ic_launcher.png"
  android: true
  web:
    generate: true
    background_color: "#FFFF00"
    theme_color: "#FFFFFF"
  windows:
    generate: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Icon/
    - assets/Icon/App/
    - assets/Placeholder/
