name: Build APK
on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Flutter
              uses: subosito/flutter-action@v1
              with:
                  flutter-version: 3.3.0
                  channel: stable
            - name: Build APK
              run: flutter build apk --release
            - name: Upload APK
              uses: actions/upload-artifact@v2
              with:
                  name: app.apk
                  path: build/app/outputs/apk/release/app-release.apk
